### ISSUE TITLE
"Flashing" powershell console

### ISSUE THREAD

**Issue by xan105** [go-toast/toast#10]
Imported "gopkg.in/toast.v1"

Maybe i'm using it wrong, but when the powershell script gets executed i can see for a fraction of a second the powershell console window ("Flashing like popup") before the toast notification. Is this an expected behaviour ?

I modified toast.go to get rid of it. I'm sharing just in case.

> toast.go

`import (
"syscall"
)`

func invokeTemporaryScript(content string) error {
	id, _ := uuid.NewV4()
	file := filepath.Join(os.TempDir(), id.String()+".ps1")
	defer os.Remove(file)
	err := ioutil.WriteFile(file, []byte(content), 0600)
	if err != nil {
		return err
	}
	`cmd := exec.Command("PowerShell", "-ExecutionPolicy", "Bypass", "-File", file)`
	`cmd.SysProcAttr = &syscall.SysProcAttr{HideWindow: true}`
	`if err = cmd.Run(); err != nil {`
		return err
	}
	return nil
}

**Comment by hebestreit** [comment]
@xan105 I've just added your changes in my branch and created pull request #12 

Thanks for sharing this solution!

**Comment by jmshal** [comment]
Thanks @xan105 for the fix and @hebestreit for creating a PR. This patch has been merged into v1.
