### ISSUE TITLE
[Encoding problem] Special characters appear like this: Ã‰

### ISSUE THREAD

**Issue by xan105** [go-toast/toast#11]
Golang doesn't support bom in utf8.
But it is much needed most of the time when reading files for Windows.
When the powershell script launches the toast, special characters (eg: é) would appear like this: Ã‰.

We need to add the bom to the temporary powershell script for the content to be properly displayed in the toast notification.

like so:

> toast.go

func invokeTemporaryScript(content string) error {
	id, _ := uuid.NewV4()
	file := filepath.Join(os.TempDir(), id.String()+".ps1")
	defer os.Remove(file)
	
	bom := []byte{0xef, 0xbb, 0xbf}
	final := append(bom, content...)
	err := ioutil.WriteFile(file, final, 0600)
	if err != nil {
		return err
	}

[...]

}

**Comment by jmshal** [comment]
Pretty sure this has been fixed in https://github.com/go-toast/toast/pull/16.

**Comment by popstas** [comment]
Will it merged to v1?
