### ISSUE TITLE
go get fails from OSX

### ISSUE THREAD

**Issue by gedw99** [go-toast/toast#14]
any ideas ?
I can build windows stuff from OSX and linux using the fabulous mingw64.

````
apple$ go get gopkg.in/toast.v1
# gopkg.in/toast.v1
../../../../../../../../../gopkg.in/toast.v1/toast.go:352:41: unknown field 'HideWindow' in struct literal of type syscall.SysProcAttr
````

Here is my make file that is using the toast lib.

https://github.com/gen2brain/beeep/issues/19

Would really appreciate help.

**Comment by gedw99** [comment]
go get fails, but cross compiling still works from osx, so closing.
raise this again if you want more info..

**Comment by McMuellermilch** [comment]
Hi @gedw99 , I get the same exact error when trying to run my linux jenkins pipeline. Do you have any more information on why this error occurs and how to bypass that?
