### ISSUE TITLE
Notifications not displaying image, message or title.

### ISSUE THREAD

**Issue by davidsbond** [go-toast/toast#5]
I have been trying to add toast notifications to an application I'm developing. Using the example in the readme the following notification is produced:

#### Notification
![toast](https://cloud.githubusercontent.com/assets/6227720/18886988/3318eeaa-84ea-11e6-9285-b73b1b6387b8.png)

#### Action Centre
![toast2](https://cloud.githubusercontent.com/assets/6227720/18887317/74c0c30e-84eb-11e6-8fc0-998b02480f45.png)

As you can see, there is no image and no action buttons. I am not sure if this is down to a setting on my machine or not. However, the code I am using is a copy/paste of the example, using the gopher image as "go.png".

I'm running Go 1.7 on Windows 64-bit.

Thanks.

**Comment by jacobmarshall** [comment]
Hi David,

Sorry about the confusion - I'm going to change that example, as it's come up a few times recently.

Basically, the image path needs to be an absolute path on the system, as the underlying PowerShell script is invoked from a temporary path, not the current working directory.

I have cleared this up in the upcoming godoc, but I still have a few places to update to some more clarity.

Thanks,
Jacob

**Comment by davidsbond** [comment]
Jacob,

Thanks for your quick response. However, when I use the following code

 	notification := toast.Notification{
		AppID:   "Example App",
		Title:   "My notification",
		Message: "Some message about how important something is...",
		Icon:    "C:\\Users\\David\\Documents\\GitHub\\dfs\\src\\go.png",
		Actions: []toast.Action{
			{"protocol", "I'm a button", ""},
			{"protocol", "Me too!", ""},
		},
	}

	err := notification.Push()

I am still presented with the same notifications that lack images or the correct text.

**Comment by jacobmarshall** [comment]
That is really odd, I see what you mean now. It looks like you haven't got the latest version of Windows 10 - what build are you on, I'll see if I can find an old `.iso` and test this in a VM.

**Comment by davidsbond** [comment]
@jacobmarshall 

I am running build 10240 of Windows 10.

**Comment by jacobmarshall** [comment]
Cheers David, and just to clarify, are you using `toast` v1 via gopkg.in, or master via github.com?

**Comment by davidsbond** [comment]
@jacobmarshall 

I am using the master via github.com

**Comment by jacobmarshall** [comment]
Cheers, I will get back to you ASAP.

In the mean time - it may also be worth trying the pre-packaged CLI exe and seeing whether *it* works. https://github.com/go-toast/toast#cli

**Comment by davidsbond** [comment]
@jacobmarshall,

The pre-packaged CLI functions as intended.

**Comment by jacobmarshall** [comment]
Thanks David, I have been able to replicate the issue - I'll update you soon when there is a resolution.

**Comment by jacobmarshall** [comment]
Hi @davidsbond,

Thanks for your patience, I have pushed a fix to `master` and plan to roll this out to `v1` after I do some more testing - however I'm pretty sure there will be no further issues.

Jacob

**Comment by davidsbond** [comment]
@jacobmarshall

Awesome, great stuff!
