### ISSUE TITLE
No Notification is shown

### ISSUE THREAD

**Issue by jessestricker** [go-toast/toast#9]
Hi,
I am using your library like this:

```go
import "github.com/go-toast/toast" // also tried "gopkg.in/toast.v1"

// ...

notification := toast.Notification{
	AppID:   "...",
	Title:   "...",
	Message: "...",
	Audio:   toast.Default,
}
err := notification.Push()
checkErr(err)
```

The notification is not shown, no sound is played and no error is returned from `notification.Push()`.  
System Info: Windows 10 (Version 1709, Build 16288.1)

I've had a glance at your code real quick, but could not see the bug myself.

**Comment by jmshal** [comment]
Thanks @jessestricker, I will investigate as soon as I can.

**Comment by jessestricker** [comment]
Maybe this has to do with me working on an Windows Insider preview version.
A friend runs the stable release version and the notification shows up on his system.

**Comment by jmshal** [comment]
Thanks for the additional information. I haven't had any chance to take a look yet. But I will keep you posted as soon as I do. I'm primarily a macOS user, so having to boot into Windows and close my 1.5 billion open Chrome tabs is hard for me 😋. Though it sounds like I'll have to setup a VM to test the insider preview version in isolation.

**Comment by Jonatino** [comment]
@jmshal this is broken on the fall creators update :)

**Comment by zwlxt** [comment]
I am using Windows 10 Version 1903 Build 18362.145 and found that I can send toast notifications using a custom AppID.

Just make sure it doesn't contain illegal characters, especially `'`. Space is legal.

![image](https://user-images.githubusercontent.com/19585961/58609330-ca983e80-82d9-11e9-8790-b0fd3492052e.png)

If you still have issues about not showing notifications, you can open %temp% and look for *.ps1 file, run it in you PowerShell console and you can see error message.

**Comment by Bebbolus** [comment]
Hi zwlxt how can you generate custom app id?

**Comment by rahul-dutt-sharma** [comment]
https://docs.microsoft.com/en-us/windows/configuration/find-the-application-user-model-id-of-an-installed-app 

the above link might help..

**Comment by jessestricker** [comment]
I am closing this as it's really out of date and the repo seems unmaintained.
